//Basic-Phrases.js
export const textData = {
    words: [
        { word: "Eu sou feliz.", translation: "I am happy.", note: "Eu sou [adjective]." },
        { word: "Eu tenho um livro.", translation: "I have a book.", note: "Eu tenho [noun]." },
        { word: "Eu gosto de pizza.", translation: "I like pizza.", note: "Eu gosto de [noun/verb+ing]." },
        { word: "Eu gosto de ler.", translation: "I like reading.", note: "Eu gosto de [noun/verb+ing]." },
        { word: "Eu não gosto de frio.", translation: "I don’t like cold weather.", note: "Eu não gosto de [noun/verb+ing]." },
        { word: "Eu quero café.", translation: "I want coffee.", note: "Eu quero [noun/verb]." },
        { word: "Eu quero dormir.", translation: "I want to sleep.", note: "Eu quero [noun/verb]." },
        { word: "Eu preciso de uma caneta.", translation: "I need a pen.", note: "Eu preciso de [noun/verb]." },
        { word: "Eu preciso ir.", translation: "I need to go.", note: "Eu preciso de [noun/verb]." },
        { word: "Eu consigo nadar.", translation: "I can swim.", note: "Eu consigo [verb]." },
        { word: "Eu não consigo dirigir.", translation: "I cannot (can’t) drive.", note: "Eu não consigo [verb]." },
        { word: "Eu vou te ligar.", translation: "I will call you.", note: "Eu vou [verb]." },
        { word: "Eu não vou lá.", translation: "I won’t go there.", note: "Eu não vou [verb]." },
        { word: "Eu vou comer.", translation: "I am going to eat.", note: "Eu vou [verb]." },
        { word: "O que é isso?", translation: "What is this?", note: "O que é [noun]?" },
        { word: "Onde está meu celular?", translation: "Where is my phone?", note: "Onde está [noun]?" },
        { word: "Quem é seu professor?", translation: "Who is your teacher?", note: "Quem é [person]?" },
        { word: "Quando é a reunião?", translation: "When is the meeting?", note: "Quando é [event]?" },
        { word: "Como está sua mãe?", translation: "How is your mom?", note: "Como está [person/thing]?" },
        { word: "Como está a comida?", translation: "How is the food?", note: "Como está [person/thing]?" },
        { word: "Posso sentar aqui?", translation: "Can I sit here?", note: "Posso [verb]?" },
        { word: "Você joga futebol?", translation: "Do you play soccer?", note: "Você [verb]?" },
        { word: "O que você gosta de comer?", translation: "What do you like to eat?", note: "O que você gosta?" },
        { word: "Como eu abro isso?", translation: "How do I open this?", note: "Como eu [verb]?" },
        { word: "É grande.", translation: "It is big.", note: "É [adjective]." },
        { word: "Não é caro.", translation: "It isn’t expensive.", note: "Não é [adjective]." },
        { word: "Isto é minha bolsa.", translation: "This is my bag.", note: "Isto é [noun]." },
        { word: "Isso é a casa dele.", translation: "That is his house.", note: "Isso é [noun]." },
        { word: "Estes são meus livros.", translation: "These are my books.", note: "Estes são [plural noun]." },
        { word: "Aqueles são meus sapatos.", translation: "Those are my shoes.", note: "Aqueles são [plural noun]." },
        { word: "Eu trabalho todo dia.", translation: "I work every day.", note: "Eu [verb] todo dia." },
        { word: "Eu estudo de manhã.", translation: "I study in the morning.", note: "Eu [verb] de manhã/tarde/noite." },
        { word: "Eu janto às 19h.", translation: "I eat dinner at 7 PM.", note: "Eu [verb] às [time]." },
        { word: "Eu jogo futebol aos sábados.", translation: "I play soccer on Saturdays.", note: "Eu [verb] aos [days of the week]." },
        { word: "São 15h.", translation: "It is 3 o’clock.", note: "São [time]." },
        { word: "Hoje é segunda-feira.", translation: "It is Monday.", note: "Hoje é [day of the week]." },
        { word: "Minha cor favorita é azul.", translation: "My favorite color is blue.", note: "Minha cor favorita é [noun]." },
        { word: "Eu prefiro chá a café.", translation: "I prefer tea to coffee.", note: "Eu prefiro [noun] a [noun]." },
        { word: "Eu amo cozinhar.", translation: "I love cooking.", note: "Eu amo [noun/verb+ing]." },
        { word: "Eu odeio esperar.", translation: "I hate waiting.", note: "Eu odeio [noun/verb+ing]." },
        { word: "Vamos sair.", translation: "Let’s go out.", note: "Vamos [verb]." },
        { word: "Que tal assistir um filme?", translation: "How about watching a movie?", note: "Que tal [verb+ing]?" },
        { word: "Por que não fazemos uma pausa?", translation: "Why don’t we take a break?", note: "Por que não [verb]?" },
        { word: "Eu estava cansada.", translation: "I was tired.", note: "Eu estava [adjective]." },
        { word: "Eu tive um ótimo tempo.", translation: "I had a great time.", note: "Eu tive [noun]." },
        { word: "Eu andei até o parque.", translation: "I walked to the park.", note: "Eu [verb+ed]." },
        { word: "Eu não vi a mensagem.", translation: "I didn’t see the message.", note: "Eu não [verb]." },
        { word: "Você tomou café da manhã?", translation: "Did you eat breakfast?", note: "Você [verb]?" },
        { word: "Eu vou visitar amanhã.", translation: "I will visit tomorrow.", note: "Eu vou [verb]." },
        { word: "Eu vou viajar.", translation: "I am going to travel.", note: "Eu vou [verb]." },
        { word: "Eu acho que vou ficar em casa.", translation: "I think I will stay home.", note: "Eu acho que vou [verb]." },
        { word: "Você vai me ajudar?", translation: "Will you help me?", note: "Você vai [verb]?" },
        { word: "Eu acho que é uma boa ideia.", translation: "I think it’s a good idea.", note: "Eu acho que [sentence]." },
        { word: "Eu não acho que vai chover.", translation: "I don’t think it will rain.", note: "Eu não acho que [sentence]." }
    ]
};
