//Travel-Phrases.js
export const textData = {
    words: [ // Even though it's a phrase, keep this named "words"
        { word: "Olá!", translation: "Hello!", note: "Used for greetings, informal or formal." },
        { word: "Oi!", translation: "Hi!", note: "More casual than 'Olá'." },
        { word: "Tudo bem?", translation: "How are you?", note: "Common Brazilian greeting." },
        { word: "Bom dia!", translation: "Good morning!", note: "Used until noon." },
        { word: "Boa tarde!", translation: "Good afternoon!", note: "Used after noon until early evening." },
        { word: "Boa noite!", translation: "Good evening/night!", note: "Used at night or as a farewell." },
        { word: "Por favor.", translation: "Please.", note: "Polite way to make requests." },
        { word: "Obrigada!", translation: "Thank you!", note: "Use 'Obrigada' if you're a woman. 'Obrigado' for men." },
        { word: "De nada.", translation: "You're welcome.", note: "Response to 'Thank you'." },
        { word: "Desculpe.", translation: "Sorry.", note: "To apologize politely." },
        { word: "Com licença.", translation: "Excuse me.", note: "Used when interrupting or passing by someone." },
        { word: "Quanto custa?", translation: "How much does it cost?", note: "Use when shopping." },
        { word: "Onde fica o banheiro?", translation: "Where is the bathroom?", note: "Essential for traveling!" },
        { word: "Eu não falo português.", translation: "I don't speak Portuguese.", note: "Useful to explain language limitations." },
        { word: "Você fala inglês?", translation: "Do you speak English?", note: "Ask for English speakers." },
        { word: "Eu preciso de ajuda.", translation: "I need help.", note: "Use in emergencies or for assistance." },
        { word: "Pode me ajudar?", translation: "Can you help me?", note: "Politely asking for help." },
        { word: "Eu estou perdida.", translation: "I am lost.", note: "Important if you lose your way." },
        { word: "Onde fica [lugar]?", translation: "Where is [place]?", note: "Replace [lugar] with a location." },
        { word: "Como chego ao hotel?", translation: "How do I get to the hotel?", note: "Ask for directions." },
        { word: "Aceita cartão?", translation: "Do you accept cards?", note: "Ask if credit/debit cards are accepted." },
        { word: "Eu quero isso, por favor.", translation: "I want this, please.", note: "Useful when pointing at something." },
        { word: "Você tem isso em outro tamanho?", translation: "Do you have this in another size?", note: "For shopping." },
        { word: "Posso experimentar?", translation: "Can I try it on?", note: "Use when trying clothes." },
        { word: "Onde posso comprar um chip de celular?", translation: "Where can I buy a SIM card?", note: "Useful for staying connected." },
        { word: "Estou com fome.", translation: "I am hungry.", note: "When you're looking for food." },
        { word: "Estou com sede.", translation: "I am thirsty.", note: "For asking for a drink." },
        { word: "Eu quero água, por favor.", translation: "I want water, please.", note: "Requesting water." },
        { word: "Tem um restaurante por aqui?", translation: "Is there a restaurant nearby?", note: "Ask for dining options." },
        { word: "O cardápio, por favor.", translation: "The menu, please.", note: "Ask for the menu." },
        { word: "Eu sou vegetariana.", translation: "I am vegetarian.", note: "Say 'vegetariano' if you're a man." },
        { word: "Quanto tempo demora para chegar?", translation: "How long does it take to get there?", note: "For transport queries." },
        { word: "Onde está o ponto de ônibus mais próximo?", translation: "Where is the nearest bus stop?", note: "For navigating public transport." },
        { word: "Eu preciso de um táxi.", translation: "I need a taxi.", note: "When requesting a taxi." },
        { word: "Chame a polícia, por favor.", translation: "Call the police, please.", note: "For emergencies." },
        { word: "Meu telefone foi roubado.", translation: "My phone was stolen.", note: "Use in case of theft." },
        { word: "Quanto custa a corrida?", translation: "How much is the ride?", note: "Ask the price of a taxi or ride-share." },
        { word: "Eu gostaria de pagar a conta.", translation: "I’d like to pay the bill.", note: "At a restaurant or café." },
        { word: "Aceita dinheiro?", translation: "Do you accept cash?", note: "Ask about payment methods." },
        { word: "Qual é o horário de funcionamento?", translation: "What are the opening hours?", note: "Ask about a store or service schedule." },
        { word: "Que horas são?", translation: "What time is it?", note: "Ask for the time." },
        { word: "Está muito quente hoje.", translation: "It’s very hot today.", note: "Talk about the weather." },
        { word: "Está frio agora.", translation: "It’s cold now.", note: "Discussing cooler weather." },
        { word: "Pode tirar uma foto para mim?", translation: "Can you take a picture for me?", note: "Ask for help with photos." },
        { word: "É minha primeira vez no Brasil.", translation: "It’s my first time in Brazil.", note: "Good for conversations." },
        { word: "Eu estou aprendendo português.", translation: "I am learning Portuguese.", note: "Encourages patience." },
        { word: "Como se diz [palavra] em português?", translation: "How do you say [word] in Portuguese?", note: "For learning new words." },
        { word: "Onde posso trocar dinheiro?", translation: "Where can I exchange money?", note: "Ask for currency exchange." },
        { word: "Onde posso carregar meu celular?", translation: "Where can I charge my phone?", note: "When your phone needs power." }
    ]
};
